# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve' or 'jekyll server --watch'. If you change this file, please restart the server process.

# Site settings
title: Quru Image Server
email: sales@quru.com
description: >
  QIS is an image server
baseurl:  # the subpath of your site, e.g. /blog
url: https://qis.app  # the base hostname & protocol for your site
twitter_username: quru
github_username:  qurusales

author:
  name:           Roland Whitehead
  url:            https://twitter.com/rolandw
  email:          i.am@rolandw.me


# Build settings
#markdown: kramdown
version: 0.1
github:
  repo: https://github.com/qurusales/qurusales.github.io
collections:
  pages:
    output: true
  blog:
    output: true
  documentation:
    output: true
  features:
    output: true
  pricing:
    output: true
  casestudies:
    output: true
